require('gramic/globals')
require('third-party-config/lsp_config')
require('third-party-config/lualine-setup')
require('third-party-config/treesitter-setup')
require('third-party-config/telescope-setup')
require('third-party-config/neogen-setup')
require('third-party-config/completions')
require('third-party-config/indent-blankline')
require('third-party-config/Comment')
-- require('third-party-config/null-ls-setup')
