require('gramic/globals')
require('third-party-config/lsp-zero-setup')
require('third-party-config/lualine-setup')
require('third-party-config/treesitter-setup')
require('third-party-config/telescope-setup')
require('third-party-config/neogen-setup')
require('third-party-config/null-ls-setup')
require('third-party-config/which-key-setup')
